### ISSUE TITLE
Is your ignore word list correct? 

### ISSUE THREAD

**Issue by fangfufu** [callumrollo/cmcrameri#33]
In your codespell [configuration](https://github.com/callumrollo/cmcrameri/blob/08ac60e0a13318b6e97587fee32402ac6a46e263/.pre-commit-config.yaml#L38), you configured it to ignore words:
```
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
    - id: codespell
      args:
        - --ignore-words-list=buda
```

Based on the [documentation](https://github.com/codespell-project/codespell#ignoring-words), this should be a word list. 

The closest ``buda`` file I can find is [here](https://github.com/callumrollo/cmcrameri/blob/08ac60e0a13318b6e97587fee32402ac6a46e263/cmcrameri/cmaps/buda.txt), it contains a list of numbers.
